// GENERATED CODE - DO NOT MODIFY BY HAND

part of 'user.dart';

// **************************************************************************
// JsonSerializableGenerator
// **************************************************************************

_$_User _$$_UserFromJson(Map<String, dynamic> json) => _$_User(
      id: json['id'] as int?,
      date: json['date'] as String?,
      active_date: json['active_date'] as String?,
      valid_date: json['valid_date'] as String?,
      type: json['type'] as String?,
      firstname: json['firstname'] as String?,
      lastname: json['lastname'] as String?,
      username: json['username'] as String?,
      nic: json['nic'] as String?,
      phonenumber: json['phonenumber'] as String?,
      whatsappnumber: json['whatsappnumber'] as String?,
      email: json['email'] as String?,
      active: json['active'] as String?,
      edit: json['edit'] as String?,
      inviteid: json['inviteid'] as String?,
      verifycode: json['verifycode'] as String?,
      verified: json['verified'] as String?,
      image: json['image'] as String?,
      bank_name: json['bank_name'] as String?,
      branch_name: json['branch_name'] as String?,
      account_name: json['account_name'] as String?,
      account_number: json['account_number'] as String?,
      bank_swift_code: json['bank_swift_code'] as String?,
      address: json['address'] as String?,
      bank_receipt_image: json['bank_receipt_image'] as String?,
      view_bank_receipt: json['view_bank_receipt'] as String?,
      payment_type: json['payment_type'] as String?,
      website: json['website'] as String?,
      company: json['company'] as String?,
      designation: json['designation'] as String?,
      birthday: json['birthday'] as String?,
      phone: json['phone'] as String?,
      country: json['country'] as String?,
      facebook: json['facebook'] as String?,
      instagram: json['instagram'] as String?,
      twitter: json['twitter'] as String?,
      linkedin: json['linkedin'] as String?,
      youtube: json['youtube'] as String?,
      about: json['about'] as String?,
      oauth_provider: json['oauth_provider'] as String?,
      oauth_uid: json['oauth_uid'] as String?,
      gender: json['gender'] as String?,
      unique_link: json['unique_link'] as String?,
      created: json['created'] as String?,
      modified: json['modified'] as String?,
      token_de_platform: json['token_de_platform'] as String?,
    );

Map<String, dynamic> _$$_UserToJson(_$_User instance) => <String, dynamic>{
      'id': instance.id,
      'date': instance.date,
      'active_date': instance.active_date,
      'valid_date': instance.valid_date,
      'type': instance.type,
      'firstname': instance.firstname,
      'lastname': instance.lastname,
      'username': instance.username,
      'nic': instance.nic,
      'phonenumber': instance.phonenumber,
      'whatsappnumber': instance.whatsappnumber,
      'email': instance.email,
      'active': instance.active,
      'edit': instance.edit,
      'inviteid': instance.inviteid,
      'verifycode': instance.verifycode,
      'verified': instance.verified,
      'image': instance.image,
      'bank_name': instance.bank_name,
      'branch_name': instance.branch_name,
      'account_name': instance.account_name,
      'account_number': instance.account_number,
      'bank_swift_code': instance.bank_swift_code,
      'address': instance.address,
      'bank_receipt_image': instance.bank_receipt_image,
      'view_bank_receipt': instance.view_bank_receipt,
      'payment_type': instance.payment_type,
      'website': instance.website,
      'company': instance.company,
      'designation': instance.designation,
      'birthday': instance.birthday,
      'phone': instance.phone,
      'country': instance.country,
      'facebook': instance.facebook,
      'instagram': instance.instagram,
      'twitter': instance.twitter,
      'linkedin': instance.linkedin,
      'youtube': instance.youtube,
      'about': instance.about,
      'oauth_provider': instance.oauth_provider,
      'oauth_uid': instance.oauth_uid,
      'gender': instance.gender,
      'unique_link': instance.unique_link,
      'created': instance.created,
      'modified': instance.modified,
      'token_de_platform': instance.token_de_platform,
    };
