name: viwaha_lk
description: A new Flutter project.

publish_to: 'none' # Remove this line if you wish to publish to pub.dev

version: 1.0.0+1

environment:
  sdk: '>=2.19.6 <3.0.0'

dependencies:
  flutter:
    sdk: flutter
  riverpod: ^1.0.3
  cupertino_icons: ^1.0.2
  auto_route: ^7.1.0
  flutter_riverpod: ^1.0.3+1
  flutter_gen: ^5.3.1
  sizer: ^2.0.15
  font_awesome_flutter: ^10.4.0
  flutter_rating_bar: ^4.0.1
  carousel_slider: ^4.2.1
  flutter_social_button: ^1.1.4+1
  url_launcher: ^6.1.11
  flutter_map: ^4.0.0
  google_maps_flutter: ^2.2.8

 


dev_dependencies:
  flutter_test:
    sdk: flutter
  build_runner: ^2.0.4
  flutter_lints: ^2.0.0
  auto_route_generator: ^7.0.0
  


flutter:
  uses-material-design: true

  assets:
    - lib/assets/images/

 