// GENERATED CODE - DO NOT MODIFY BY HAND

part of 'top_listing.dart';

// **************************************************************************
// JsonSerializableGenerator
// **************************************************************************

_$_TopListing _$$_TopListingFromJson(Map<String, dynamic> json) =>
    _$_TopListing(
      id: json['id'] as String?,
      datetime: json['datetime'] as String?,
      user_id: json['user_id'] as String?,
      title: json['title'] as String?,
      category: json['category'] as String?,
      main_category: json['main_category'] as String?,
      address: json['address'] as String?,
      location: json['location'] as String?,
      main_location: json['main_location'] as String?,
      video: json['video'] as String?,
      name: json['name'] as String?,
      email: json['email'] as String?,
      phone: json['phone'] as String?,
      whatsapp: json['whatsapp'] as String?,
      website: json['website'] as String?,
      designation: json['designation'] as String?,
      company: json['company'] as String?,
      facebook: json['facebook'] as String?,
      instagram: json['instagram'] as String?,
      youtube: json['youtube'] as String?,
      linkedin: json['linkedin'] as String?,
      description: json['description'] as String?,
      amenities: json['amenities'] as String?,
      saturday_open_time: json['saturday_open_time'] as String?,
      saturday_close_time: json['saturday_close_time'] as String?,
      sunday_open_time: json['sunday_open_time'] as String?,
      sunday_close_time: json['sunday_close_time'] as String?,
      monday_open_time: json['monday_open_time'] as String?,
      monday_close_time: json['monday_close_time'] as String?,
      tuesday_open_time: json['tuesday_open_time'] as String?,
      tuesday_close_time: json['tuesday_close_time'] as String?,
      wednesday_open_time: json['wednesday_open_time'] as String?,
      wednesday_close_time: json['wednesday_close_time'] as String?,
      thursday_open_time: json['thursday_open_time'] as String?,
      thursday_close_time: json['thursday_close_time'] as String?,
      friday_open_time: json['friday_open_time'] as String?,
      friday_close_time: json['friday_close_time'] as String?,
      always_open: json['always_open'] as String?,
      open_holiday: json['open_holiday'] as String?,
      images: json['images'] as String?,
      thumb_images: json['thumb_images'] as String?,
      views: json['views'] as String?,
      active: json['active'] as String?,
      premium: json['premium'] as String?,
      bank_receipt_image: json['bank_receipt_image'] as String?,
      price: json['price'] as String?,
      ask_price: json['ask_price'] as String?,
      negotiable: json['negotiable'] as String?,
    );

Map<String, dynamic> _$$_TopListingToJson(_$_TopListing instance) =>
    <String, dynamic>{
      'id': instance.id,
      'datetime': instance.datetime,
      'user_id': instance.user_id,
      'title': instance.title,
      'category': instance.category,
      'main_category': instance.main_category,
      'address': instance.address,
      'location': instance.location,
      'main_location': instance.main_location,
      'video': instance.video,
      'name': instance.name,
      'email': instance.email,
      'phone': instance.phone,
      'whatsapp': instance.whatsapp,
      'website': instance.website,
      'designation': instance.designation,
      'company': instance.company,
      'facebook': instance.facebook,
      'instagram': instance.instagram,
      'youtube': instance.youtube,
      'linkedin': instance.linkedin,
      'description': instance.description,
      'amenities': instance.amenities,
      'saturday_open_time': instance.saturday_open_time,
      'saturday_close_time': instance.saturday_close_time,
      'sunday_open_time': instance.sunday_open_time,
      'sunday_close_time': instance.sunday_close_time,
      'monday_open_time': instance.monday_open_time,
      'monday_close_time': instance.monday_close_time,
      'tuesday_open_time': instance.tuesday_open_time,
      'tuesday_close_time': instance.tuesday_close_time,
      'wednesday_open_time': instance.wednesday_open_time,
      'wednesday_close_time': instance.wednesday_close_time,
      'thursday_open_time': instance.thursday_open_time,
      'thursday_close_time': instance.thursday_close_time,
      'friday_open_time': instance.friday_open_time,
      'friday_close_time': instance.friday_close_time,
      'always_open': instance.always_open,
      'open_holiday': instance.open_holiday,
      'images': instance.images,
      'thumb_images': instance.thumb_images,
      'views': instance.views,
      'active': instance.active,
      'premium': instance.premium,
      'bank_receipt_image': instance.bank_receipt_image,
      'price': instance.price,
      'ask_price': instance.ask_price,
      'negotiable': instance.negotiable,
    };
